from selenium.webdriver.common.by import By

class Locators:
    BUTTON_LOGIN = (By.XPATH, "//button[contains(text(), 'Вход и регистрация')]")
    BUTTON_CREATE_AD = (By.XPATH, "//button[contains(text(), 'Разместить объявление')]")
    USER_AVATAR = (By.XPATH, "//button[@class='circleSmall']")
    USER_NAME = (By.XPATH, "//h3[@class='profileText name']")
    BUTTON_LOGOUT = (By.XPATH, "//button[contains(text(), 'Выйти')]")
    BUTTON_NEXT_PAGE = (By.XPATH, "//button[@class='arrowButton arrowButton--right undefined']")
    TEXT_AD_ERROR = (By.XPATH, "//h1[contains(@class, 'h1') and contains(text(), 'Чтобы разместить объявление, авторизуйтесь')]")
    AD_ERROR_WINDOW = (By.XPATH, "//form[contains(@class, 'popUp_shell__LuyqR')]")
    BUTTON_NO_ACCOUNT = (By.XPATH, "//button[contains(text(), 'Нет аккаунта')]")
    BUTTON_CREATE_ACCOUNT = (By.XPATH, "//button[contains(text(), 'Создать аккаунт')]")
    SUBMIT_LOGIN_BUTTON = (By.XPATH, "//button[contains(text(), 'Войти')]")
    INPUT_EMAIL = (By.NAME, "email")
    INPUT_PASSWORD = (By.NAME, "password")
    INPUT_CONFIRM_PASSWORD = (By.NAME, "submitPassword")
    TEXT_EMAIL_ERROR = (By.XPATH, "//span[@class='input_span__yWPqB' and text()='Ошибка']")
    TEXT_ERROR_MESSAGE = (By.XPATH, "//span[contains(text(), 'Логин или пароль неверны')]")
    TEXT_MYAD_SECTION = (By.XPATH, "//h1[contains(text(), 'Мои объявления')]")
    AD_TITLE_AND_CITY = (By.XPATH, "//div[@class='description']")
    AD_PRICE_TEXT = (By.XPATH, "//div[@class='price']")
    AD_NAME = (By.XPATH, "//input[@class='input_inputStandart__JweLZ spanGlobal']")
    AD_DESCRIPTION = (By.XPATH, "//textarea[@placeholder='Описание товара']")
    MY_AD_CARD_BY_TITLE = (By.CSS_SELECTOR, "div[class*='grid_threeColumns'] .card")
    AD_PRICE_INPUT = (By.NAME, "price")
    BUTTON_DROPDOWN_CITY = (By.CSS_SELECTOR, "input[name='city'] + button")
    DROPDOWN_CHOOSE_CITY_VALUE = (By.XPATH, "//span[contains(text(), 'Москва')]")
    INPUT_DROPDOWN_CATEGORY = (By.CSS_SELECTOR, "input[name='category'] + button")
    TEXT_DROPDOWN_CHOOSE_CATEGORY = (By.XPATH, "//span[contains(text(), 'Технологии')]")
    INPUT_RADIOBUTTON_AD = (By.CLASS_NAME, "radioUnput_inputRegular__FbVbr")
    BUTTON_AD_PUBLISH = (By.XPATH, "//button[contains(text(), 'Опубликовать')]")
